/* =========================================================================
   Anthropic GitHub Field Guide — データ定義
   - REPOS  : 全90リポジトリ（2026-06時点・公開分）
   - CATS   : カテゴリ定義
   - PILLARS: 4本柱（つくる / つかう / まなぶ / しらべる）
   - PATHS  : 実務シナリオ別の学習ロードマップ
   - USECASES: トップで見せる「実務での使いどころ」
   短縮キー: n=name s=stars l=language c=category v=level o=official(自社製) j=説明 u=実務での使いどころ t=tags
   ========================================================================= */

const PILLARS = [
  { id:'build',    jp:'つくる',   en:'Build',  cats:['code','sdk','mcp','fun'],
    lead:'Claudeで開発する',
    desc:'Claude Code、エージェントSDK、各言語の公式SDK、MCP連携。コードを書く人の中核ツール群。' },
  { id:'use',      jp:'つかう',   en:'Use',    cats:['skills','industry'],
    lead:'業務で使う',
    desc:'Skills・Plugins・Cowork、そして法務／金融／医療などの業界特化ソリューション。非エンジニアの活用もここ。' },
  { id:'learn',    jp:'まなぶ',   en:'Learn',  cats:['learn'],
    lead:'学ぶ・教材',
    desc:'クックブック、公式コース、対話型チュートリアル、すぐ動くクイックスタート。スキルの底上げに。' },
  { id:'research', jp:'しらべる', en:'Trust',  cats:['security','research'],
    lead:'安全性と研究',
    desc:'セキュリティ・自動レビュー、解釈可能性、評価（eval）、安全性研究の論文と資料。' },
];

const CATS = {
  code:     { label:'Claude Code・エージェント', pillar:'build' },
  sdk:      { label:'公式SDK・API',             pillar:'build' },
  mcp:      { label:'MCP連携',                  pillar:'build' },
  fun:      { label:'話題・実験',                pillar:'build' },
  skills:   { label:'Skills・Plugins・Cowork',  pillar:'use' },
  industry: { label:'業界特化',                  pillar:'use' },
  learn:    { label:'学習・教材',                pillar:'learn' },
  security: { label:'セキュリティ',              pillar:'research' },
  research: { label:'研究・論文・評価',          pillar:'research' },
  infra:    { label:'OSS・インフラ',             pillar:'infra' },
};

const REPOS = [
  /* ---------------- BUILD : Claude Code・エージェント ---------------- */
  { n:'claude-code', s:132144, l:'Python', c:'code', v:'入門', o:true,
    j:'ターミナルで動く本家のエージェント型コーディングツール。コードベースを理解し、自然言語で開発作業を代行する。',
    u:'日々のコーディング・リファクタ・Git操作・調査を任せ、制作スピードを底上げする中核ツール。',
    t:['Claude Code','エージェント','CLI'] },
  { n:'claude-code-action', s:7983, l:'TypeScript', c:'code', v:'実践', o:true,
    j:'Claude CodeをGitHub Actionsに組み込む公式アクション。',
    u:'PRレビュー・Issue対応・自動修正をCIに組み込み、リポジトリ運用そのものを自動化。',
    t:['Claude Code','CI/CD','GitHub'] },
  { n:'claude-code-base-action', s:871, l:'TypeScript', c:'code', v:'応用', o:true,
    j:'claude-code-action内のbase-actionミラー。低レベルにClaude Codeを呼ぶ土台。',
    u:'独自ワークフローからClaude Codeを直接起動したいときの基盤として。',
    t:['Claude Code','CI/CD'] },
  { n:'claude-agent-sdk-python', s:7291, l:'Python', c:'code', v:'実践', o:true,
    j:'自作AIエージェントを構築する公式SDK（Python）。Claude Codeと同じ基盤。',
    u:'自動化ツールや社内エージェントをPythonで内製する出発点。',
    t:['Agent SDK','Python','エージェント'] },
  { n:'claude-agent-sdk-typescript', s:1527, l:'TypeScript', c:'code', v:'実践', o:true,
    j:'Agent SDKのTypeScript版。Web/Node環境でエージェントを構築。',
    u:'Webアプリやサーバーレスにエージェント機能を組み込む。',
    t:['Agent SDK','TypeScript','エージェント'] },
  { n:'claude-agent-sdk-demos', s:2511, l:'TypeScript', c:'code', v:'入門', o:true,
    j:'Agent SDKの実装デモ集。動くサンプルから設計を学べる。',
    u:'内製の前に典型パターンを写経して、エージェント設計の感覚を掴む。',
    t:['Agent SDK','サンプル'] },
  { n:'agent-sdk-workshop', s:37, l:'Python', c:'code', v:'入門', o:true,
    j:'Agent SDKを段階的に学ぶワークショップ教材。',
    u:'ハンズオン形式でエージェント構築を一から習得。',
    t:['Agent SDK','ワークショップ'] },
  { n:'devcontainer-features', s:273, l:'Shell', c:'code', v:'応用', o:true,
    j:'Claude Code CLIを含むDev Container Features。',
    u:'VS Code / Codespacesの開発環境にClaude Codeを標準搭載する。',
    t:['Claude Code','DevContainer','環境構築'] },
  { n:'riv2025-long-horizon-coding-agent-demo', s:66, l:'Python', c:'code', v:'応用', o:true,
    j:'長時間・長工程タスクをこなすコーディングエージェントのデモ。',
    u:'大規模な移行・リファクタなど、長丁場の自動化を設計する参考に。',
    t:['エージェント','デモ'] },

  /* ---------------- BUILD : MCP ---------------- */
  { n:'claude-ai-mcp', s:329, l:'Markdown', c:'mcp', v:'応用', o:true,
    j:'ClaudeのMCP連携に関する不具合を報告するためのリポジトリ。',
    u:'MCP接続でつまずいたときの既知問題・報告先として参照。',
    t:['MCP','サポート'] },
  { n:'github-mcp-server', s:112, l:'Go', c:'mcp', v:'実践', o:true,
    j:'GitHub公式のMCPサーバー（Anthropicがミラー）。',
    u:'ClaudeからGitHubを操作するMCPの導入・参考実装に。',
    t:['MCP','GitHub'] },

  /* ---------------- BUILD : 公式SDK・API ---------------- */
  { n:'anthropic-sdk-python', s:3619, l:'Python', c:'sdk', v:'入門', o:true,
    j:'Claude APIをPythonから使う公式SDK。',
    u:'PythonでのAI機能実装の標準入口。バッチ処理・分析スクリプトに。',
    t:['SDK','Python','API'] },
  { n:'anthropic-sdk-typescript', s:1999, l:'TypeScript', c:'sdk', v:'入門', o:true,
    j:'Claude APIをTypeScript/JSから使う公式SDK。',
    u:'WebアプリやNodeサーバーにAI機能を組み込む標準SDK。',
    t:['SDK','TypeScript','API'] },
  { n:'anthropic-sdk-go', s:1095, l:'Go', c:'sdk', v:'実践', o:true,
    j:'Claude APIのGo公式SDK。',
    u:'高性能・常駐サービスにAIを組み込む。',
    t:['SDK','Go','API'] },
  { n:'anthropic-sdk-java', s:328, l:'Kotlin', c:'sdk', v:'実践', o:true,
    j:'Claude APIのJava / Kotlin公式SDK。',
    u:'企業システムやAndroid周辺へのAI組み込み。',
    t:['SDK','Java','API'] },
  { n:'anthropic-sdk-ruby', s:346, l:'Ruby', c:'sdk', v:'実践', o:true,
    j:'Claude APIのRuby公式SDK。',
    u:'Rails等のRubyアプリにAI機能を追加。',
    t:['SDK','Ruby','API'] },
  { n:'anthropic-sdk-csharp', s:296, l:'C#', c:'sdk', v:'実践', o:true,
    j:'Claude APIのC#公式SDK。',
    u:'.NET / Unity系アプリへのAI組み込み。',
    t:['SDK','C#','API'] },
  { n:'anthropic-sdk-php', s:158, l:'PHP', c:'sdk', v:'実践', o:true,
    j:'Claude APIのPHP公式SDK。',
    u:'WordPress / Laravel等のPHP案件にAIを組み込む。',
    t:['SDK','PHP','API'] },
  { n:'anthropic-bedrock-python', s:58, l:'Python', c:'sdk', v:'応用', o:true,
    j:'AWS Bedrock経由でClaudeを使うPython向けライブラリ。',
    u:'AWS基盤・エンタープライズ要件でClaudeを使う。',
    t:['SDK','Bedrock','AWS'] },
  { n:'anthropic-bedrock-typescript', s:29, l:'TypeScript', c:'sdk', v:'応用', o:true,
    j:'AWS Bedrock経由でClaudeを使うTypeScript向けライブラリ。',
    u:'AWS上のWebサービスでClaudeを呼ぶ。',
    t:['SDK','Bedrock','AWS'] },
  { n:'anthropic-tokenizer-typescript', s:107, l:'TypeScript', c:'sdk', v:'応用', o:true,
    j:'Claude向けトークナイザ（TypeScript）。',
    u:'トークン数の見積り・コスト試算・入力長の制御に。',
    t:['トークン','コスト管理'] },
  { n:'anthropic-cli', s:516, l:'Go', c:'sdk', v:'実践', o:true,
    j:'Claude APIを叩く公式CLI。',
    u:'ターミナルから素早くAPIを試す・スクリプトに組み込む。',
    t:['CLI','API'] },
  { n:'anthropic-tools', s:392, l:'Python', c:'sdk', v:'応用', o:true,
    j:'ツール利用（function calling）の初期サンプル／ユーティリティ。',
    u:'Claudeに外部ツールを使わせる実装の参考に。',
    t:['ツール利用','Python'] },
  { n:'apitools', s:21, l:'Python', c:'sdk', v:'応用', o:true,
    j:'API周りの補助ツール群。',
    u:'API運用の細かな作業を補助。',
    t:['API','ツール'] },
  { n:'ClaudeForFoundationModels', s:63, l:'Swift', c:'sdk', v:'応用', o:true,
    j:'AppleのFoundation Models frameworkからClaudeを使うための対応。',
    u:'iOS / macOSのネイティブアプリにClaudeを統合。',
    t:['SDK','Apple','Swift'] },

  /* ---------------- BUILD : 話題・実験 ---------------- */
  { n:'claudes-c-compiler', s:2707, l:'Rust', c:'fun', v:'研究', o:true,
    j:'Claude Opus 4.6がRustで一から書いた依存ゼロのCコンパイラ。x86/ARM/RISC-V対応で、起動可能なLinuxカーネルをコンパイルできる。',
    u:'AIがどこまで複雑な実装を書けるかの実例。設計・コード品質を読む教材として。',
    t:['話題','Rust','コンパイラ'] },

  /* ---------------- USE : Skills・Plugins・Cowork ---------------- */
  { n:'skills', s:150116, l:'Python', c:'skills', v:'入門', o:true,
    j:'Agent Skills（再利用可能なスキル）の公開リポジトリ。全リポジトリ中で最多スター。',
    u:'Claudeに専門手順を覚えさせる「スキル」を導入・自作し、業務を定型化する。',
    t:['Skills','エージェント'] },
  { n:'claude-plugins-official', s:30028, l:'Python', c:'skills', v:'入門', o:true,
    j:'Anthropic管理の公式プラグインディレクトリ。',
    u:'厳選プラグインを導入し、Claude Code / Coworkの機能を拡張する。',
    t:['Plugins','公式'] },
  { n:'claude-plugins-community', s:180, l:'Markdown', c:'skills', v:'入門', o:true,
    j:'コミュニティ製プラグインのマーケット（読み取り専用ミラー）。',
    u:'コミュニティ拡張を探す・自作プラグインを投稿する入口。',
    t:['Plugins','コミュニティ'] },
  { n:'knowledge-work-plugins', s:20481, l:'Python', c:'skills', v:'実践', o:true,
    j:'ナレッジワーカー向けプラグイン集（Claude Cowork用）。',
    u:'リサーチ・資料作成・営業など、非開発業務をプラグインで効率化。',
    t:['Plugins','Cowork','業務効率'] },
  { n:'cwc-workshops', s:1024, l:'TypeScript', c:'skills', v:'入門', o:true,
    j:'Claude Cowork（CwC）のワークショップ教材。',
    u:'Coworkの活用法をハンズオンで学ぶ。',
    t:['Cowork','ワークショップ'] },
  { n:'cwc-long-running-agents', s:426, l:'Shell', c:'skills', v:'応用', o:true,
    j:'Coworkで長時間動くエージェントの実装例。',
    u:'数時間かかる業務を任せる常駐エージェント設計の参考に。',
    t:['Cowork','エージェント'] },
  { n:'claude-desktop-buddy', s:2246, l:'C++', c:'skills', v:'応用', o:true,
    j:'Cowork / Desktop向けBluetooth APIの参考実装・サンプル（メイカー向け）。',
    u:'デスクトップ版Claudeと物理デバイスを連携させる実験に。',
    t:['Desktop','Bluetooth','IoT'] },

  /* ---------------- USE : 業界特化 ---------------- */
  { n:'financial-services', s:31011, l:'Python', c:'industry', v:'実践', o:true,
    j:'金融サービス向けのプラグイン／ソリューション一式。',
    u:'金融データ分析・レポーティング業務にClaudeを導入する。',
    t:['業界特化','金融'] },
  { n:'claude-for-legal', s:8250, l:'Python', c:'industry', v:'実践', o:true,
    j:'法務ワークフロー向けのプラグイン群。',
    u:'契約レビュー・法務リサーチなどを効率化する。',
    t:['業界特化','法務'] },
  { n:'life-sciences', s:451, l:'Python', c:'industry', v:'応用', o:true,
    j:'Claude for Life Sciences向けのマーケットプレイス。',
    u:'ライフサイエンス分野のMCP／プラグイン導入の入口。',
    t:['業界特化','ライフサイエンス'] },
  { n:'healthcare', s:300, l:'Python', c:'industry', v:'応用', o:true,
    j:'ヘルスケア領域向けのリポジトリ。',
    u:'医療・ヘルスケア業務へのClaude活用の参考に。',
    t:['業界特化','医療'] },

  /* ---------------- LEARN : 学習・教材 ---------------- */
  { n:'claude-cookbooks', s:45366, l:'Jupyter Notebook', c:'learn', v:'入門', o:true,
    j:'Claude活用の実践レシピ集（旧 anthropic-cookbook）。',
    u:'RAG・ツール利用・画像処理など、やりたい実装の写経元として最強。',
    t:['教材','レシピ','Notebook'] },
  { n:'prompt-eng-interactive-tutorial', s:36322, l:'Jupyter Notebook', c:'learn', v:'入門', o:true,
    j:'対話型のプロンプトエンジニアリング・チュートリアル。',
    u:'プロンプト設計の基礎を体系的に習得。回答品質を上げる土台。',
    t:['教材','プロンプト'] },
  { n:'courses', s:21825, l:'Jupyter Notebook', c:'learn', v:'入門', o:true,
    j:'Anthropic公式の教育コース教材。',
    u:'API・プロンプト・評価などを順番に学ぶ。',
    t:['教材','コース'] },
  { n:'claude-quickstarts', s:17004, l:'Python', c:'learn', v:'入門', o:true,
    j:'デプロイ可能なアプリをすぐ作れるクイックスタート集。',
    u:'カスタマーサポートbot等の雛形から、案件を即着手する。',
    t:['教材','クイックスタート','サンプルアプリ'] },
  { n:'anthropic-retrieval-demo', s:195, l:'Python', c:'learn', v:'応用', o:true,
    j:'検索・RAGをClaudeで試す軽量デモ（Elasticsearch / ベクタDB / Web / Wikipedia）。',
    u:'社内ドキュメント検索・RAG構築の出発点に。',
    t:['教材','RAG','検索'] },
  { n:'html-effectiveness', s:174, l:'HTML', c:'learn', v:'応用', o:true,
    j:'プロンプトでのHTML（構造化）活用の効果を示す例。',
    u:'プロンプトを構造化して回答品質を上げるテクの参考に。',
    t:['教材','プロンプト','HTML'] },
  { n:'original_performance_takehome', s:3891, l:'Python', c:'learn', v:'研究', o:true,
    j:'Anthropicの採用課題（パフォーマンス最適化）を一般公開したもの。',
    u:'腕試し・最適化スキルの訓練教材として挑戦する。',
    t:['教材','チャレンジ'] },

  /* ---------------- TRUST : セキュリティ ---------------- */
  { n:'defending-code-reference-harness', s:5800, l:'Python', c:'security', v:'実践', o:true,
    j:'脅威モデリング・スキャン・トリアージ・パッチのスキル群＋自律スキャンハーネス。/customizeで自社向けに調整可。',
    u:'コードベースの脆弱性を継続的に自動スキャン・修正する防御基盤に。',
    t:['セキュリティ','スキャン','エージェント'] },
  { n:'claude-code-security-review', s:5215, l:'Python', c:'security', v:'実践', o:true,
    j:'Claudeでコード変更をセキュリティレビューするGitHub Action。',
    u:'PRごとに脆弱性を自動チェックし、混入を未然に防ぐ。',
    t:['セキュリティ','CI/CD','レビュー'] },
  { n:'scone-bench', s:21, l:'Python', c:'security', v:'研究', o:true,
    j:'スマートコントラクトの脆弱性発見・攻略でLLMエージェントを評価するベンチマーク。',
    u:'Web3 / 監査領域でのAIエージェント性能の参考指標。',
    t:['セキュリティ','ベンチ','Web3'] },
  { n:'claude-code-monitoring-guide', s:327, l:'Markdown', c:'security', v:'応用', o:true,
    j:'Claude Codeの利用をモニタリングするためのガイド。',
    u:'組織導入時の利用状況・コスト・安全性の可視化に。',
    t:['セキュリティ','運用','ガバナンス'] },

  /* ---------------- TRUST : 研究・論文・評価 ---------------- */
  { n:'claude-constitution', s:95, l:'Markdown', c:'research', v:'入門', o:true,
    j:'Claudeの価値観と振る舞いを記した基盤文書「憲法」。',
    u:'Claudeの設計思想を理解し、期待値と限界を正しく見積もる。',
    t:['研究','価値観','ドキュメント'] },
  { n:'model-cards', s:22, l:'Markdown', c:'research', v:'入門', o:true,
    j:'Claudeモデルカードの補足資料。',
    u:'各モデルの特性・制約を確認してモデル選定の判断に。',
    t:['研究','モデル','ドキュメント'] },
  { n:'evals', s:396, l:'Python', c:'research', v:'応用', o:true,
    j:'各種評価（eval）に関するリポジトリ。',
    u:'モデル・エージェントの評価設計の参考に。',
    t:['研究','評価'] },
  { n:'political-neutrality-eval', s:133, l:'Python', c:'research', v:'応用', o:true,
    j:'政治的中立性を評価するpaired prompts手法の実装情報。',
    u:'モデルの中立性・バイアス評価の手法を学ぶ。',
    t:['研究','評価','バイアス'] },
  { n:'rogue-deploy-eval', s:15, l:'Python', c:'research', v:'研究', o:true,
    j:'逸脱デプロイ（rogue deploy）を評価するeval。',
    u:'エージェントの安全性評価手法の参考に。',
    t:['研究','評価','安全性'] },
  { n:'hh-rlhf', s:1838, l:'Data', c:'research', v:'研究', o:true,
    j:'「Helpful and Harmless」RLHF論文の人間嗜好データ。',
    u:'RLHF・アライメント研究やデータセットの参照に。',
    t:['研究','RLHF','データセット'] },
  { n:'ConstitutionalHarmlessnessPaper', s:262, l:'Paper', c:'research', v:'研究', o:true,
    j:'Constitutional AI（憲法的AI）論文の補足資料。',
    u:'AIの自己規律・安全化手法を学ぶ。',
    t:['研究','アライメント'] },
  { n:'sleeper-agents-paper', s:147, l:'Paper', c:'research', v:'研究', o:true,
    j:'「Sleeper Agents」論文で参照されるサンプル群。',
    u:'安全学習でも消えない欺瞞的振る舞いの研究を追う。',
    t:['研究','安全性'] },
  { n:'sycophancy-to-subterfuge-paper', s:27, l:'Paper', c:'research', v:'研究', o:true,
    j:'報酬ハッキングの段階的悪化を扱う論文の資料。',
    u:'AIの報酬ハッキング・逸脱挙動の研究参照に。',
    t:['研究','安全性'] },
  { n:'DecompositionFaithfulnessPaper', s:33, l:'Python', c:'research', v:'研究', o:true,
    j:'推論の分解と忠実性に関する論文の資料。',
    u:'Chain-of-Thoughtの忠実性研究の参照に。',
    t:['研究','推論'] },
  { n:'toy-models-of-superposition', s:153, l:'Jupyter Notebook', c:'research', v:'研究', o:true,
    j:'論文「Toy Models of Superposition」付随のノートブック。',
    u:'解釈可能性（重ね合わせ）の基礎を手を動かして理解。',
    t:['研究','解釈可能性'] },
  { n:'attribution-graphs-frontend', s:99, l:'JavaScript', c:'research', v:'研究', o:true,
    j:'Attribution Graphs手法のフロントエンド（transformer-circuits）。',
    u:'モデル内部の回路可視化研究を追う。',
    t:['研究','解釈可能性','可視化'] },
  { n:'headvis', s:34, l:'Svelte', c:'research', v:'研究', o:true,
    j:'アテンションヘッド等を可視化するツールの公開版。',
    u:'Transformerの内部挙動を可視化して理解する。',
    t:['研究','可視化'] },
  { n:'PySvelte', s:222, l:'Python', c:'research', v:'応用', o:true,
    j:'PythonとHTML/JS（Svelte）を橋渡しし、対話的可視化を作るライブラリ。',
    u:'研究・分析結果のインタラクティブ可視化を手軽に作る。',
    t:['研究','可視化','ツール'] },

  /* ---------------- INFRA : OSSフォーク／ミラー・自社インフラ ---------------- */
  { n:'buffa', s:770, l:'Rust', c:'infra', v:'参考', o:true,
    j:'editions対応・JSON・ゼロコピービュー付きのRust製protobuf実装（自社製）。', u:'', t:['Rust','protobuf','自社'] },
  { n:'connect-rust', s:421, l:'Rust', c:'infra', v:'参考', o:true,
    j:'ConnectRPCプロトコルのRust実装（自社製）。', u:'', t:['Rust','RPC','自社'] },
  { n:'cargo-nix-plugin', s:28, l:'Rust', c:'infra', v:'参考', o:true,
    j:'Cargoワークスペースをネイティブ解決するNixプラグイン（自社製）。', u:'', t:['Rust','Nix','自社'] },
  { n:'riegeli-rs', s:4, l:'Rust', c:'infra', v:'参考', o:true,
    j:'高効率レコード形式Riegeliのrust実装。', u:'', t:['Rust','データ','自社'] },
  { n:'tailscale-hint-extension', s:19, l:'HTML', c:'infra', v:'参考', o:true,
    j:'Tailscaleの.localドメイン解決失敗時にヒントを出すChrome拡張（社内ツール）。', u:'', t:['社内ツール','Chrome拡張'] },
  { n:'homebrew-tap', s:20, l:'Ruby', c:'infra', v:'参考', o:true,
    j:'Anthropicツール用のHomebrew formulae。', u:'', t:['Homebrew','配布'] },
  { n:'homebrew-claude', s:11, l:'Ruby', c:'infra', v:'参考', o:true,
    j:'Claude関連のHomebrew tap。', u:'', t:['Homebrew','配布'] },
  { n:'cfaulthandler', s:11, l:'Python', c:'infra', v:'参考', o:true,
    j:'Python標準のfaulthandlerに加え、C側コールスタックも出力するモジュール。', u:'', t:['Python','デバッグ'] },
  { n:'tokio', s:19, l:'Rust', c:'infra', v:'参考', o:false,
    j:'Rust製の非同期ランタイムTokioのfork。', u:'', t:['fork','Rust'] },
  { n:'triton', s:25, l:'C++', c:'infra', v:'参考', o:false,
    j:'GPUカーネル記述言語Tritonの開発リポジトリ（fork）。', u:'', t:['fork','GPU'] },
  { n:'beam', s:14, l:'Java', c:'infra', v:'参考', o:false,
    j:'統合データ処理モデルApache Beamのfork。', u:'', t:['fork','データ処理'] },
  { n:'argo-cd', s:14, l:'Go', c:'infra', v:'参考', o:false,
    j:'Kubernetes向け宣言的CDツールArgo CDのfork。', u:'', t:['fork','k8s'] },
  { n:'rclone', s:35, l:'Go', c:'infra', v:'参考', o:false,
    j:'クラウドストレージ同期ツールrcloneのfork。', u:'', t:['fork','ストレージ'] },
  { n:'redis-py', s:17, l:'Python', c:'infra', v:'参考', o:false,
    j:'Redis Pythonクライアントのfork。', u:'', t:['fork','Redis'] },
  { n:'orjson', s:55, l:'Python', c:'infra', v:'参考', o:false,
    j:'高速JSONライブラリorjsonのfork。', u:'', t:['fork','JSON'] },
  { n:'terragrunt', s:12, l:'Go', c:'infra', v:'参考', o:false,
    j:'Terraform/OpenTofuオーケストレーションTerragruntのfork。', u:'', t:['fork','IaC'] },
  { n:'maestro', s:19, l:'Java', c:'infra', v:'参考', o:false,
    j:'NetflixのワークフローオーケストレータMaestroのfork。', u:'', t:['fork','ワークフロー'] },
  { n:'s5cmd', s:37, l:'Go', c:'infra', v:'参考', o:false,
    j:'高速S3操作CLI s5cmdのfork。', u:'', t:['fork','S3'] },
  { n:'httpcore', s:16, l:'Python', c:'infra', v:'参考', o:false,
    j:'最小HTTPクライアントhttpcoreのfork。', u:'', t:['fork','HTTP'] },
  { n:'hypercorn', s:19, l:'Python', c:'infra', v:'参考', o:false,
    j:'ASGI/WSGIサーバーHypercornのfork。', u:'', t:['fork','サーバー'] },
  { n:'swift-markdown', s:7, l:'Swift', c:'infra', v:'参考', o:false,
    j:'Markdown解析のSwiftパッケージのfork。', u:'', t:['fork','Swift'] },
  { n:'swift-markdown-ui', s:51, l:'Swift', c:'infra', v:'参考', o:false,
    j:'SwiftUIでMarkdownを表示するライブラリのfork。', u:'', t:['fork','SwiftUI'] },
  { n:'sse-starlette', s:9, l:'Python', c:'infra', v:'参考', o:false,
    j:'Starlette向けSSE（Server-Sent Events）ライブラリのfork。', u:'', t:['fork','SSE'] },
  { n:'python-tblib', s:12, l:'Python', c:'infra', v:'参考', o:false,
    j:'例外・トレースバックをシリアライズするtblibのfork。', u:'', t:['fork','Python'] },
  { n:'torchtyping', s:11, l:'Python', c:'infra', v:'参考', o:false,
    j:'テンソルのshape/dtype注釈と動的チェックのfork。', u:'', t:['fork','PyTorch'] },
  { n:'blobfile', s:11, l:'Python', c:'infra', v:'参考', o:false,
    j:'クラウド／ローカルを透過的に扱うファイルIO blobfileのfork。', u:'', t:['fork','ストレージ'] },
  { n:'nix-eval-jobs', s:8, l:'Nix', c:'infra', v:'参考', o:false,
    j:'Nixを並列評価しJSONをストリーム出力するツールのfork。', u:'', t:['fork','Nix'] },
  { n:'leptos-chartistry', s:0, l:'Rust', c:'infra', v:'参考', o:false,
    j:'LeptosのチャートライブラリChartistryのfork。', u:'', t:['fork','Rust'] },
];

/* ---------------- 実務での使いどころ（トップ用） ---------------- */
const USECASES = [
  { num:'A', title:'受託・制作を加速する',
    desc:'コーディング・サイト構築・リファクタをClaude Codeに任せ、納期を縮める。',
    repos:['claude-code','claude-quickstarts','claude-code-action'] },
  { num:'B', title:'アプリ／プロダクトに組み込む',
    desc:'各言語の公式SDKでAI機能を実装。RAGやツール利用まで。',
    repos:['anthropic-sdk-typescript','claude-cookbooks','anthropic-retrieval-demo'] },
  { num:'C', title:'業務を自動化する',
    desc:'Cowork・Skills・プラグインで、非開発業務まで効率化する。',
    repos:['skills','knowledge-work-plugins','claude-plugins-official'] },
  { num:'D', title:'自律エージェントを作る',
    desc:'Agent SDKで社内エージェントや長時間タスクを内製する。',
    repos:['claude-agent-sdk-python','claude-agent-sdk-demos','cwc-long-running-agents'] },
  { num:'E', title:'安全に運用する',
    desc:'セキュリティ自動レビューとモニタリングで品質・安全を担保。',
    repos:['claude-code-security-review','defending-code-reference-harness','claude-code-monitoring-guide'] },
  { num:'F', title:'スキルを底上げする',
    desc:'クックブック・チュートリアル・コースで体系的に学ぶ。',
    repos:['prompt-eng-interactive-tutorial','courses','claude-cookbooks'] },
];

/* ---------------- 実務ロードマップ ---------------- */
const PATHS = [
  { id:'start', num:'01', title:'はじめの一歩', audience:'全員 / 非エンジニアも',
    goal:'Claudeとは何かを掴み、最初の成果物を作るまで。',
    steps:[
      { repo:'claude-constitution', why:'Claudeの価値観と限界を知り、何を任せられるか判断する。' },
      { repo:'prompt-eng-interactive-tutorial', why:'プロンプトの基礎を体系的に習得する。' },
      { repo:'claude-cookbooks', why:'やりたいことに近いレシピを写経して感覚を掴む。' },
      { repo:'claude-quickstarts', why:'動くアプリの雛形から、最初の成果物を作る。' },
    ] },
  { id:'web', num:'02', title:'受託・Web制作を加速する', audience:'制作・受託',
    goal:'日々の制作にClaude Codeを組み込み、納品・運用まで自動化する。',
    steps:[
      { repo:'claude-code', why:'まず日々のコーディング・調査・Git操作に導入する。' },
      { repo:'courses', why:'API・プロンプト・評価の基礎を押さえる。' },
      { repo:'claude-quickstarts', why:'雛形をベースに納品物を素早く立ち上げる。' },
      { repo:'claude-code-action', why:'PRレビューや定型作業をCIで自動化する。' },
      { repo:'claude-code-security-review', why:'納品前に脆弱性を自動チェックする。' },
    ] },
  { id:'product', num:'03', title:'プロダクトにAIを組み込む', audience:'アプリ／API開発',
    goal:'自社・受託プロダクトにAI機能を実装し、コストまで管理する。',
    steps:[
      { repo:'anthropic-sdk-typescript', why:'WebやNodeにAI機能を組み込む標準SDKを押さえる。' },
      { repo:'claude-cookbooks', why:'RAG・ツール利用など実装パターンを取り込む。' },
      { repo:'anthropic-retrieval-demo', why:'社内ドキュメント検索・RAGの土台を作る。' },
      { repo:'anthropic-tools', why:'外部ツール連携（function calling）を実装する。' },
      { repo:'anthropic-tokenizer-typescript', why:'トークン数を見積り、コストを管理する。' },
    ] },
  { id:'agent', num:'04', title:'自律エージェントを構築する', audience:'自動化・内製',
    goal:'社内エージェントや長時間タスクをこなす仕組みを内製する。',
    steps:[
      { repo:'claude-agent-sdk-demos', why:'まず動くデモで典型パターンを把握する。' },
      { repo:'agent-sdk-workshop', why:'ワークショップで設計を体系的に学ぶ。' },
      { repo:'claude-agent-sdk-python', why:'PythonでエージェントをScratchから実装する。' },
      { repo:'riv2025-long-horizon-coding-agent-demo', why:'長工程タスクの設計を学ぶ。' },
      { repo:'cwc-long-running-agents', why:'常駐・長時間運用の形に落とし込む。' },
    ] },
  { id:'automate', num:'05', title:'業務を自動化する', audience:'非エンジニア歓迎',
    goal:'コードを書かずに、日々の業務をCowork・プラグインで効率化する。',
    steps:[
      { repo:'cwc-workshops', why:'Coworkの基本をハンズオンで学ぶ。' },
      { repo:'knowledge-work-plugins', why:'リサーチ・資料作成などの業務プラグインを導入する。' },
      { repo:'claude-plugins-official', why:'公式の厳選プラグインで機能を拡張する。' },
      { repo:'skills', why:'自社の手順を「スキル」化して定型業務を自動化する。' },
    ] },
  { id:'industry', num:'06', title:'業界特化で導入する', audience:'法務／金融／医療など',
    goal:'業界特化ソリューションを自社業務に合わせて導入する。',
    steps:[
      { repo:'financial-services', why:'金融向けの分析・レポーティングを導入する。' },
      { repo:'claude-for-legal', why:'契約レビュー等、法務ワークフローを効率化する。' },
      { repo:'life-sciences', why:'ライフサイエンス向けのMCP／プラグインを導入する。' },
      { repo:'claude-code-monitoring-guide', why:'導入後の利用状況・安全性を監視する。' },
    ] },
  { id:'safety', num:'07', title:'安全性と研究を学ぶ', audience:'研究志向・品質担当',
    goal:'AIの安全性・アライメントの考え方と評価手法を理解する。',
    steps:[
      { repo:'claude-constitution', why:'設計思想（憲法）から安全性の前提を知る。' },
      { repo:'ConstitutionalHarmlessnessPaper', why:'Constitutional AIの仕組みを学ぶ。' },
      { repo:'hh-rlhf', why:'RLHFの嗜好データで学習の実際に触れる。' },
      { repo:'toy-models-of-superposition', why:'解釈可能性の基礎を手を動かして理解する。' },
      { repo:'evals', why:'モデル・エージェントの評価設計を学ぶ。' },
    ] },
];

/* グローバル公開 */
window.GUIDE = { PILLARS, CATS, REPOS, USECASES, PATHS };
